Makefile, docker-compose.yml
env param added to docker-compose.yml.
docker compose env file option added
=> .env파일 분할 및 Makefile --env-file 옵션 추가.

Makefile, backend/back/src/auth/auth.controller.ts
redir path added from config
Makefile up will copy development.yml
=> Makefile 수정 및 Redirection 경로 업데이트

backend/back/package-lock.json, backend/back/package.json, backend/back/src/main.ts
=> MYM-50-BE-swagger

backend/back/src/auth/auth.service.ts, backend/back/src/auth/jwt-2fa/jwt-2fa.strategy.ts, backend/back/src/auth/jwt/jwt.strategy.ts, backend/back/src/auth/local/local.strategy.ts, backend/back/src/login/login.controller.ts, backend/back/src/user/user.service.ts
1. 2fa 로직을 조금 더 명료하게 변경
2. 이전 풀리퀘에서 빠졌던 예외처리 및 함수 이동
=> MYM-53 login logic refactoring

frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/components/LoginPage/SignIn.tsx, frontend/front/src/components/LoginPage/TwoFactorAuth.tsx, frontend/front/src/pages/LoginPage.tsx, frontend/front/src/styles/LoginModals.css
=> Mym 56 login page

frontend/front/src/components/ChatPage/ChatArea.tsx, frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/components/LoginPage/TwoFactorAuth.tsx, frontend/front/src/styles/ChatArea.css, frontend/front/src/styles/LoginModals.css
ChatPage, LoginModal 에서 <input type="text"> css 똑같이해놔서 같이 적용되던거 className으로 분리함
=> [fix] Input type text -> className 통일

frontend/front/src/components/GamePage/CheckBox.tsx, frontend/front/src/components/GamePage/GameInfo.ts, frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/GamePage/Pong.tsx, frontend/front/src/components/GamePage/Waiting.tsx, frontend/front/src/styles/GameInfo.css, frontend/front/src/styles/PingPong.css
기존에 canvas가 보이지 않았던 것과 checkbox를 빼먹은 부분 수정 및 추가해서 올렸습니다!
=> Mym 55 fe game page add CheckBox, fix PingPong canvas

frontend/front/package-lock.json, frontend/front/package.json, frontend/front/src/App.tsx, frontend/front/src/components/ChatPage/ChatRoomList.tsx, frontend/front/src/components/ChatPage/ChatRoomUserList.tsx, frontend/front/src/components/ChatPage/ChatUserList.tsx, frontend/front/src/components/ChatPage/RoomInviteModal.tsx, frontend/front/src/components/ChatPage/RoomModal.tsx, frontend/front/src/components/ChatPage/UserInfoModal.tsx, frontend/front/src/components/atom/ModalAtom.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/styles/ChatList.css, frontend/front/src/styles/NickNameModal.css, frontend/front/src/styles/RoomInviteModal.css, frontend/front/src/styles/RoomModal.css, frontend/front/src/styles/UserInfoModal.css
localhost:3000/chat의 3가지 modal
1. 화면 우측 user list의 user를 클릭하면 유저정보를 표시
2. 화면 좌측 상단 Chatting List의 +버튼을 클릭하면 새로운 방을 생성
3. 화면 우측 roomName의 +버튼을 클릭하면 새로운 유저 추가
=> Mym 63 fe chat page modal

backend/back/src/app.module.ts, backend/back/src/auth/auth.module.ts, backend/back/src/auth/auth.service.ts, backend/back/src/auth/local/local.strategy.ts, backend/back/src/game/game.module.ts, backend/back/src/login/login.controller.ts, backend/back/src/login/login.module.ts, backend/back/src/user/user.controller.ts, backend/back/src/user/user.module.ts, backend/back/src/user/user.service.ts
- 모듈관계 정리
- User에서 AuthService 를 사용하도록 메소드 이동 및 변경
- login controller 에 있던 메소드들, user service로 대거 이동
=> Mym 72 be module 

backend/back/src/auth/auth.module.ts, backend/back/src/login/login.module.ts
- jwtService reigster error fix
=> MYM-75-BE-hotfix-JWTService-keyerror

docker-compose.yml, frontend/front/src/components/TopBar.tsx, frontend/front/src/styles/TopBar.css
=> MYM-76 add link

frontend/front/src/components/ProfilePage/ChangNameModal.tsx, frontend/front/src/components/ProfilePage/ProfileOptions.tsx, frontend/front/src/components/atom/ModalAtom.ts, frontend/front/src/pages/ProfilePage.tsx, frontend/front/src/styles/ProfileModal.css, frontend/front/src/styles/ProfilePage.css
간단하게 change name modal만 켜지게 했습니다!
=> MYM-81 change name modal on

frontend/front/src/components/ChatPage/ChatArea.tsx, frontend/front/src/components/ChatPage/ChatRoomList.tsx, frontend/front/src/components/ChatPage/ChatRoomUserList.tsx, frontend/front/src/components/ChatPage/ChatUserList.tsx, frontend/front/src/components/objects/ChatRoom.tsx, frontend/front/src/components/objects/SpeechBubble.tsx, frontend/front/src/components/objects/UserObj.tsx, frontend/front/src/styles/ChatArea.css, frontend/front/src/styles/ChatRoom.css, frontend/front/src/styles/SpeechBubble.css, frontend/front/src/styles/UserObj.css
CharPage에 User객체, Room객체, 말풍선 만들어봤읍니다
=> Mym 87 fe user state chat room speech bubble

frontend/front/src/components/ChatPage/ChatRoomUserList.tsx, frontend/front/src/components/ChatPage/ChatUserList.tsx, frontend/front/src/components/GamePage/PlayerRecordBoard.tsx, frontend/front/src/components/GamePage/Waiting.tsx, frontend/front/src/components/ProfilePage/ProfileFriend.tsx, frontend/front/src/components/ProfilePage/ProfileMatchHistory.tsx, frontend/front/src/components/atom/UserAtom.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/pages/GamePage.tsx, frontend/front/src/styles/GamePlayerInfo.css, frontend/front/src/styles/ProfilePage.css
=> Mym 92 fe game log

frontend/front/src/components/GamePage/GameInfo.ts, frontend/front/src/components/GamePage/Pong.tsx, frontend/front/src/components/ProfilePage/ProfileFriend.tsx
게임화면 일단은 피그마랑 동일하게 맞춰놨고
프로필페이지 친구목록에서 UserObj가 null일경우 에러떠서 처리했습니다
=> Mym 97 fe fix game table

frontend/front/src/components/TopBar.tsx
🎉100번째🎉 기능은 로그아웃을 눌렀을때 로그인창으로 넘어가는 간단한 기능입니다!
=> MYM-100 [add] logout logic

frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/GamePage/Pong.tsx, frontend/front/src/components/ProfilePage/ProfileMatchHistory.tsx, frontend/front/src/components/atom/GameAtom.ts
이제 왼쪽 게임판 위아래 방향키로 움직일수 잇음니다
소켓으로 게임좌표 받아다가 GameCoordinateAtom 갱신해주고 Game(gameInfo) 호출해주면 될듯
=> [fix] now can move PingPongPad

frontend/front/src/components/ProfilePage/ChangeNameModal.tsx
닉네임 변환해서 DB에 올리는 것까지 했습니다!
TODO: 채팅페이지 소켓으로 바뀐 닉네임 갱신
=> Mym 104 fe change nickname

backend/back/config/default.yml, backend/back/package-lock.json, backend/back/package.json, backend/back/src/app.controller.ts, backend/back/src/app.module.ts, backend/back/src/app.service.ts, backend/back/src/cache/cache.service.ts, backend/back/src/cache/memory.module.ts
기본적인 CacheModule 추가
키 밸류값 저장
메소드는 추가 작성 예정
메세지에 따라 다르게 작성될 예정
=> MYM-102 cache module added

backend/back/src/auth/auth.service.ts, backend/back/src/login/login.controller.ts, backend/back/src/user/dto/ChangeNickname.dto.ts, backend/back/src/user/dto/TokenSet.dto.ts, backend/back/src/user/dto/TwoFactorConfirm.dto.ts, backend/back/src/user/user.controller.ts, backend/back/src/user/user.service.ts
- swagger API 부분 설명 추가
- 로그인, 이중인증 부분 컨트롤러 수정 및 token 리턴 하는 부분 dto 추가
- follow unfollow 할때, uid 받아서 가변파라메터로 작동
=> MYM-106 user API description add and refactors

backend/back/src/database/database.service.ts, backend/back/src/database/entity/direct-message.entity.ts, backend/back/src/database/entity/user.entity.ts
/tester/addUser 
로 요청시, 계정생성 + 로그인 (쿠키에 access token 추가)
=> Mym 114 be test account

backend/back/src/game/game.service.ts, frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/GamePage/Pong.tsx, frontend/front/src/components/atom/GameAtom.ts
=> [fix] PingPong canvas leaeaks

frontend/front/src/App.tsx, frontend/front/src/components/LoginPage/InitialSetting.tsx
닉변로직 추가했습니다.
오류처리는 했는데 아마 뭔가 오류가 있겠죠..
첫로그인시 닉/프로필변경페이지로 넘기는 방식에 대해선 논의가 필요
=> [add] change nickname logic

frontend/front/src/App.tsx, frontend/front/src/components/GamePage/GameResultModal.tsx, frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/pages/GamePage.tsx, frontend/front/src/styles/TopBar.css
게임페이지에서 로딩창(랭킹), 게임결과모달 토글버튼 추가
첫 로그인시 프사 입력 안해도 진행되도록 수정
=> Mym 121 fe game loding lobby

frontend/front/src/components/GamePage/GameInviteModal.tsx, frontend/front/src/components/atom/ModalAtom.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/styles/GameInviteModal.css, frontend/front/src/styles/GameResultModal.css
ChatPage는 디버깅용 버튼만 추가했는데 그.. Pritter 때문에 암튼 많이 바뀐것이니 무시바랍니다..
게임초대는 모든 화면에서 받을 수 있으니
ChatPage에도 있고 ProfilePage에도 있던지
App.tsx 레벨에 있던지 해야할거같습니다.
인자로 받는 from:은 상대방 닉네임이구요
AcceptBtn 은 Accept 누를때 실행될 콜백함수입니다.
게임수락 + 게임창 이동 로직 들어가면 될거같구요
DeclineBtn 은 Decline  누르면 실행될 콜백함수입니다.
게임거절 로직만 넣으면 됩니다.
=> Mym 123 fe game invite modal

backend/back/src/socket/chat.gateway.ts, frontend/front/src/components/ChatPage/RoomInviteModal.tsx, frontend/front/src/components/ChatPage/UserInfoModal.tsx, frontend/front/src/components/objects/UserObj.tsx, frontend/front/src/event/api.request.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/socket/chat.socket.ts, frontend/front/src/styles/ChatRoomUserList.css, frontend/front/src/styles/SpeechBubble.css
* ignore 추가
* invite 추가
---
* dm은 추가가 많을 것 같아서 브랜치 새로해 작업하겠습니다.
=> Mym 122 ignore & invite

backend/back/src/socket/chat.gateway.ts, frontend/front/src/components/ChatPage/ChatArea.tsx, frontend/front/src/components/ChatPage/ChatRoomList.tsx, frontend/front/src/components/ChatPage/ChatRoomUserList.tsx, frontend/front/src/components/ChatPage/RoomModal.tsx, frontend/front/src/components/atom/ChatAtom.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/socket/chat.dto.ts, frontend/front/src/socket/chat.socket.ts
* roomInfo change button 동작 
* 이전과 변경 없으면 에러
* `open`방 ->
* `password` 설정시 -> `protected`
* `private` button 설정시 -> `private`
* `password` + `private` button 설정시 -> `private`
* `private`방 ->
*  `password` 설정시 ->  `private`(비번은 저장됨)
*   `private` button `uncheck` -> `open` (비번이 걸려있어도 `open`)
* `protected`방 ->
* `password` -> 값 없으면 그대로 (에러),
* `private` button `check` -> `private`
=> Mym 126 fe room info change

frontend/front/src/components/ChatPage/ChatArea.tsx, frontend/front/src/components/ChatPage/ChatRoomList.tsx, frontend/front/src/components/ChatPage/ChatRoomUserList.tsx, frontend/front/src/components/ChatPage/ChatUserList.tsx, frontend/front/src/components/ChatPage/PasswordModal.tsx, frontend/front/src/components/ChatPage/RoomInviteModal.tsx, frontend/front/src/components/ChatPage/RoomModal.tsx, frontend/front/src/components/ChatPage/UserInfoModal.tsx, frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/components/LoginPage/Register.tsx, frontend/front/src/components/ProfilePage/ChangeImageModal.tsx, frontend/front/src/components/ProfilePage/ChangeNameModal.tsx, frontend/front/src/components/TopBar.tsx, frontend/front/src/components/atom/ChatAtom.ts, frontend/front/src/event/event.util.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/pages/GamePage.tsx, frontend/front/src/pages/LoginPage.tsx, frontend/front/src/socket/chat.socket.ts, frontend/front/src/socket/game.socket.ts
* `F4` key event로 `on | off` (adminConsoleAtom<boolean>)
* AdminLogPrinter로 log 출력
* chatPage, gamePage 적용 완료.
---
* 한글 입력 중복 -> `inputbox` 에서 `onKeyDown` -> `onKeyPress`로 변경 후 해결
---
* gamePage에서 `ping: sec/ms`는 eventListener가 uesEffect로 안 감싸져 있어서..
=> Mym 132 fe admin console 

frontend/front/src/components/ChatPage/UserInfoModal.tsx
=> [fix] profile img size

backend/back/src/database/database.service.ts, backend/back/src/user/dto/UserProfile.dto.ts, backend/back/src/user/user.controller.ts, backend/back/src/user/user.service.ts
=> Mym 129 be game status 

backend/back/src/socket/chat.gateway.ts, frontend/front/src/components/ChatPage/ChatRoomUserList.tsx, frontend/front/src/components/ChatPage/ChatUserList.tsx, frontend/front/src/pages/ChatPage.tsx
* 처음으로 Dm 한 유저가 나가버리면 UserList의 DmList에 안보이는 문제
* 해결: front-side에서 dmHistoryList에 저장
---
* UserList 정렬 추가
* roomUserList 정렬 추가
=> first DM user add to DmUserList in front-side also change color

Makefile, frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/components/LoginPage/SignIn.tsx, frontend/front/src/components/ProfilePage/ChangeImageModal.tsx, frontend/front/src/components/ProfilePage/ChangeNameModal.tsx, frontend/front/src/components/TopBar.tsx, frontend/front/src/event/api.request.ts, frontend/front/src/socket/chat.socket.ts, frontend/front/src/socket/game.socket.ts
http://localhost:4000 까지 URL
config/.front.env 파일에 있는거 front/.env 로 복사해서
process.env.REACT_APP_API_URL 로 쓸수 있게 해두고 여태 있던 리터럴주소는 다 바꿨읍니다.
환경변수 이름은 반드시 REACT_APP_ 으로 시작해야함미다
=> [fix] http://localhost:4000 to process.env.REACT_APP_API_URL

backend/back/src/user/user.controller.ts
=> MYM-140 add other user me

backend/back/src/main.ts
=> MYM-141 validation pipe add

frontend/front/src/components/TopBar.tsx, frontend/front/src/pages/ChatPage.tsx
=> isMyProfile move to Topbar in profile button

backend/back/src/auth/jwt-Initial/jwt-Initial.auth.guard.ts, backend/back/src/auth/jwt-Initial/jwt-Initial.strategy.ts, backend/back/src/auth/jwt-refresh/jwt-refresh.strategy.ts, backend/back/src/auth/jwt/jwt.strategy.ts, backend/back/src/user/user.controller.ts, backend/back/src/user/user.module.ts
=> MYM-146 inital strategy add & nickname valid check

frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/pages/GamePage.tsx
=> [fix] GamePage issue

frontend/front/package-lock.json, frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/components/atom/LoginAtom.ts, frontend/front/src/pages/LoginPage.tsx
이제 닉네임에 # 붙어있으면 InitialSetting페이지 뜹니다.
=> Mym 150 fe initial setting logic

backend/back/src/socket/chat.gateway.ts, frontend/front/package-lock.json, frontend/front/src/components/ChatPage/PasswordModal.tsx, frontend/front/src/components/ProfilePage/ProfileFriend.tsx, frontend/front/src/event/api.request.ts, frontend/front/src/pages/ChatPage.tsx, frontend/front/src/socket/chat.socket.ts
* refresh 해결 (간혹  `socket`이 2개 열리고 연결시도하는 케이스가 있어서, connect하는 곳에 딜레이를 주어서 해결)
* multiple-login 위와 비슷한 로직으로 해결
* m1 및 클러스터 테스트 완료 ><
* password modal auto focus
* password modal quit : 비번 입력중에, 방이 삭제되거나, 업데이트되면
=> MYM-138-BE-refresh

backend/back/src/auth/auth.service.ts, backend/back/src/user/user.service.ts
=> MYM-151 verify logic changed

backend/back/src/game/game.enum.ts, backend/back/src/game/game.gateway.ts, backend/back/src/game/game.service.ts, frontend/front/src/components/ChatPage/UserInfoModal.tsx, frontend/front/src/components/atom/GameAtom.ts, frontend/front/src/pages/GamePage.tsx
1. 게임소켓이 계속 polling 되는 이슈때문에 gameSocketAtom을 추가
2. SPEED 모드 추가 (테스트 필요)
=> Mym 118 be game queue elo 

backend/back/src/database/database.service.ts, backend/back/src/game/game.service.ts
=> MYM-128 game data transaction added

backend/back/src/game/game.service.ts, frontend/front/src/components/GamePage/GameInfo.ts, frontend/front/src/components/GamePage/GameResultModal.tsx, frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/GamePage/Pong.tsx, frontend/front/src/components/atom/GameAtom.ts, frontend/front/src/pages/GamePage.tsx
1. Animation 중복되던 버그 픽스.
2. 결과 출력창 정상 출력.
=> Mym 128 all game event control

backend/back/src/game/game.gateway.ts, backend/back/src/game/game.service.ts, frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/GamePage/Waiting.tsx, frontend/front/src/components/atom/GameAtom.ts, frontend/front/src/pages/GamePage.tsx
1. 관전자 모드 버그 픽스
2. [BE] socket emit 위치를 update후 setTimeout후에 하도록 변경.
- 카운트 다운할떄 syncData 에러 간헐적 발생... 수정 예정.
=> Mym 165 all add observer mode

backend/back/src/chat/chat.gateway.ts, backend/back/src/game/game.gateway.ts, frontend/front/src/components/ChatPage/UserInfoModal.tsx, frontend/front/src/components/GamePage/GameResultModal.tsx, frontend/front/src/components/GamePage/LadderBoard.tsx, frontend/front/src/components/GamePage/Waiting.tsx, frontend/front/src/components/ProfilePage/ChangeNameModal.tsx, frontend/front/src/components/TopBar.tsx, frontend/front/src/components/atom/ChatAtom.ts, frontend/front/src/pages/ChatWrapper.tsx, frontend/front/src/pages/GamePage.tsx, frontend/front/src/socket/chat.dto.ts
* leaderBoard 반영 (로그인시 + 1분마다 chatServer에서 업데이트 알림)
* 관전하는 유저를 invite시 observ되던 에러 해결
=> Mym 166 fe game records display

backend/back/src/chat/chat.gateway.ts, frontend/front/src/components/GamePage/GameInfo.ts, frontend/front/src/components/GamePage/LadderBoard.tsx, frontend/front/src/components/GamePage/Pong.tsx, frontend/front/src/pages/GamePage.tsx
* cavas에 이름, 카운트 넣기
* 랭킹 숫자 1부터
=> Mym 167 fe display name and count

frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/styles/PingPong.css
atom같은거 하나 만들어서 카운트마다 숫자 바뀌게 설정하시면 될것 같습니다..
=> MYM-168 CountDown on PingPong.tsx + css

backend/back/src/database/database.service.ts, backend/back/src/database/entity/game.entity.ts, backend/back/src/database/entity/user-follow.entity.ts, backend/back/src/database/entity/user.entity.ts, backend/back/src/user/dto/UserProfile.dto.ts, backend/back/src/user/user.service.ts
/user/me 조회 로직 수정
- user me 조회시, game table join 하여 조회
- userfollowing 도 같이 조회하려 했으나, 순환참조 문제인것으로 추정되어 join 하여 참조가 안됨
- 따라서 userfollowing 테이블은 따로 조회로 내비둠
=> Mym 161 be user me game

backend/back/src/game/game.gateway.ts
=> Mym 169 all emit bug fix

backend/back/src/chat/chat.gateway.ts, backend/back/src/game/game.gateway.ts, frontend/front/src/components/ChatPage/UserInfoModal.tsx, frontend/front/src/components/GamePage/GameInviteModal.tsx, frontend/front/src/components/GamePage/PingPong.tsx, frontend/front/src/components/GamePage/PlayerRecordBoard.tsx, frontend/front/src/components/GamePage/Waiting.tsx, frontend/front/src/components/LoginPage/InitialSetting.tsx, frontend/front/src/components/ProfilePage/ChangeNameModal.tsx, frontend/front/src/components/ProfilePage/ProfileFriend.tsx, frontend/front/src/components/ProfilePage/ProfileMatchHistory.tsx, frontend/front/src/components/atom/UserAtom.ts, frontend/front/src/event/api.request.ts, frontend/front/src/pages/ChatWrapper.tsx, frontend/front/src/styles/GamePlayerInfo.css, frontend/front/src/styles/PingPong.css
* gameHistory 추가 (profile, match)
* gameMode 표시 추가 (N, S)
* /user/me DTO 변경에 따른 수정 (userInfo, Following, GameRecord 분리 - 이전엔 한번에)
---
* 최초 로그인시 nickName 중복체크 추가
=> Mym 170 fe game records 

backend/back/src/chat/chat.gateway.ts
=> edit roomInvite who is offline user
